package edu.wctc;

public class LastNameUtility {
    final private Algorithm soundex = new Algorithm();

    public static String encodeLastName(String lastname) throws MissingNameException {
        //	If the last name is blank, throws a MissingNameException. Returns the encoding of the last name generated by the Soundex algorithm.
        if (lastname == null || lastname.isEmpty()) {
            throw new MissingNameException("Last name");
        } else {
            return Algorithm.createSoundex(lastname);
        }
    }
}
